### ISSUE TITLE
Test doesn't build with quickcheck-instances 0.3.28

### ISSUE THREAD

**Issue by felixonmars** [phadej/binary-orphans#59]
We should probably tighten the bounds to >= 0.3.29

```
[1 of 1] Compiling Main             ( test/Tests.hs, dist/build/binary-orphans-test/binary-orphans-test-tmp/Main.dyn_o )

test/Tests.hs:30:5: error:
    • No instance for (Test.QuickCheck.Arbitrary.Arbitrary ByteArray)
        arising from a use of ‘testProperty’
      There are instances for similar types:
        instance Test.QuickCheck.Arbitrary.Arbitrary
                   primitive-0.7.4.0:Data.Primitive.ByteArray.ByteArray
          -- Defined in ‘Test.QuickCheck.Instances.Primitive’
    • In the first argument of ‘($)’, namely ‘testProperty "ByteArray"’
      In the expression:
        testProperty "ByteArray" $ roundtrip (Proxy :: Proxy ByteArray)
      In the second argument of ‘testGroup’, namely
        ‘[testProperty "Natural" $ roundtrip (Proxy :: Proxy Natural),
          testProperty "Sum Int" $ roundtrip (Proxy :: Proxy (Sum Int)),
          testProperty "Min Int" $ roundtrip (Proxy :: Proxy (Min Int)),
          testProperty "Solo Int" $ roundtrip (Proxy :: Proxy (Solo Int)),
          ....]’
   |
30 |   , testProperty "ByteArray"       $ roundtrip (Proxy :: Proxy ByteArray)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ 
```
